name: Build iOS

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - run: npm install
      
      - run: npx cap add ios
      
      - run: npx cap build ios
      
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ios/App/build/App.ipa
